name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'a14'

jobs:
  build_lavender:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [SM-G9910, SM-G9960, SM-G9980]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang golang libbrotli-dev \
            libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev libzstd-dev \
            linux-modules-extra-$(uname -r) build-essential lld ninja-build protobuf-compiler zipalign gcc-aarch64-linux-gnu
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Fetch WeebX Clang
        run: |
          wget "$(curl -s https://raw.githubusercontent.com/XSans0/WeebX-Clang/main/main/link.txt)" -O "weebx-clang.tar.gz"
          mkdir clang && tar -xf weebx-clang.tar.gz -C clang && rm -rf weebx-clang.tar.gz
          
      - name: Fetch AnyKernel3
        run: |
          git clone https://github.com/LucasBlackLu/AnyKernel3 -b wip ./Anykernel3
          
      - name: Build Kernel Clean
        run: |
          source ./build_script.sh ${{ matrix.target }}
          cp ./AnyKernel3/Lavender* ./
      - name: Clean Kernel Source
        run: |
          make mrproper ARCH=arm64 LLVM=1
          
      - name: Build Kernel With KSU
        run: |
          source ./build_script.sh ${{ matrix.target }} --ksu
          cp ./AnyKernel3/Lavender* ./
          
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: Lavender*
          name: Lavender-CI_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Kernel: 5.4.259
            Clang: WeebX
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
